config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message, only: [:create, :show, :edit, :update, :destroy]
  before_action :find_comment, only: [:edit, :show, :update, :destroy]
  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
    @message = Message.find(params[:message_id])
  end

  def find_comment
    @comment = @message.comments.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order('created_at DESC')
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end

  def find_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div>
  <p>
    <%= comment.content %>
  </p>
  <p>By: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
  <div>
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to 'Edit', edit_message_comment_path(comment.message, comment) %>
        <%= link_to 'Delete', message_comments_path(comment.message, comment), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: 'Comments' %>
  <%= f.button :submit, class: 'btn btn-primary'  %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for ([@message, @comment]) do |f| %>
  <%= f.input :content, label: 'Comments' %>
  <%= f.button :submit, class: 'btn btn-primary'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav navbar-default">
    <div class="container">
      <%= link_to 'Forum', root_path, class: 'navbar-brand' %>

      <ul class="navbar-nav nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <p>
          <%= link_to 'New Post', new_message_path, class: 'navbar-text navbar-link' %>
        </p>
      <% end %>
    </div>

  </div>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: 'Message Title' %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit Message</h1>
  <%= render 'form' %>
</div>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%= message.title %></h2>
      </div>
      <p class="panel-body">
        <%= message.description %>
      </p>
      <div class="panel-footer">
        <%= link_to 'View Post', message, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Post Message</h1>
  <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2><%= @message.title %></h2>
    </div>
    <div class="panel-body">
      <p><%= @message.description %></p>

      <% unless @message.comments.blank? %>
        <h3>Comments:</h3>
        <p><%= render @message.comments %></p>
      <% end %>
      <% if user_signed_in? %>
        <h4>Reply</h4>
        <%= render 'comments/form' %>
      <% end %>
    </div>
    <div class="panel-footer">
      <p>
        <%= time_ago_in_words(@message.created_at) %> ago
      </p>
      <div class="btn-group">
        <%= link_to 'List', root_path, class: 'btn btn-default' %>
        <% if user_signed_in? %>
          <% if @message.user_id == current_user.id %>
            <%= link_to 'Edit', edit_message_path(@message), class: 'btn btn-primary' %>
            <%= link_to 'Delete', { action: :destroy, id: @message.id }, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>